import type { TarotCardMeta } from './types'

export const TAROT_CARD_FACE_BASE_PATH = '/assets/tarot/cards'

export const TAROT_CARDS = [
  {
    id: 'major-00-fool',
    deckIndex: 0,
    arcana: 'major',
    suit: null,
    number: 0,
    rank: 'major',
    nameZh: '愚者',
    nameEn: 'The Fool',
    uprightKeywordsZh: ['新开始', '自由', '冒险', '信任'],
  },
  {
    id: 'major-01-magician',
    deckIndex: 1,
    arcana: 'major',
    suit: null,
    number: 1,
    rank: 'major',
    nameZh: '魔术师',
    nameEn: 'The Magician',
    uprightKeywordsZh: ['显化', '行动', '资源', '创造'],
  },
  {
    id: 'major-02-high-priestess',
    deckIndex: 2,
    arcana: 'major',
    suit: null,
    number: 2,
    rank: 'major',
    nameZh: '女祭司',
    nameEn: 'The High Priestess',
    uprightKeywordsZh: ['直觉', '潜意识', '神秘', '静观'],
  },
  {
    id: 'major-03-empress',
    deckIndex: 3,
    arcana: 'major',
    suit: null,
    number: 3,
    rank: 'major',
    nameZh: '皇后',
    nameEn: 'The Empress',
    uprightKeywordsZh: ['丰饶', '滋养', '美感', '创造力'],
  },
  {
    id: 'major-04-emperor',
    deckIndex: 4,
    arcana: 'major',
    suit: null,
    number: 4,
    rank: 'major',
    nameZh: '皇帝',
    nameEn: 'The Emperor',
    uprightKeywordsZh: ['秩序', '权威', '稳定', '领导力'],
  },
  {
    id: 'major-05-hierophant',
    deckIndex: 5,
    arcana: 'major',
    suit: null,
    number: 5,
    rank: 'major',
    nameZh: '教皇',
    nameEn: 'The Hierophant',
    uprightKeywordsZh: ['传统', '信仰', '教导', '规范'],
  },
  {
    id: 'major-06-lovers',
    deckIndex: 6,
    arcana: 'major',
    suit: null,
    number: 6,
    rank: 'major',
    nameZh: '恋人',
    nameEn: 'The Lovers',
    uprightKeywordsZh: ['爱', '契合', '选择', '价值观'],
  },
  {
    id: 'major-07-chariot',
    deckIndex: 7,
    arcana: 'major',
    suit: null,
    number: 7,
    rank: 'major',
    nameZh: '战车',
    nameEn: 'The Chariot',
    uprightKeywordsZh: ['意志', '胜利', '掌控', '前进'],
  },
  {
    id: 'major-08-strength',
    deckIndex: 8,
    arcana: 'major',
    suit: null,
    number: 8,
    rank: 'major',
    nameZh: '力量',
    nameEn: 'Strength',
    uprightKeywordsZh: ['勇气', '耐心', '温柔力量', '自制'],
  },
  {
    id: 'major-09-hermit',
    deckIndex: 9,
    arcana: 'major',
    suit: null,
    number: 9,
    rank: 'major',
    nameZh: '隐者',
    nameEn: 'The Hermit',
    uprightKeywordsZh: ['内省', '独处', '智慧', '指引'],
  },
  {
    id: 'major-10-wheel-of-fortune',
    deckIndex: 10,
    arcana: 'major',
    suit: null,
    number: 10,
    rank: 'major',
    nameZh: '命运之轮',
    nameEn: 'Wheel of Fortune',
    uprightKeywordsZh: ['转机', '周期', '命运', '变化'],
  },
  {
    id: 'major-11-justice',
    deckIndex: 11,
    arcana: 'major',
    suit: null,
    number: 11,
    rank: 'major',
    nameZh: '正义',
    nameEn: 'Justice',
    uprightKeywordsZh: ['公正', '因果', '真相', '责任'],
  },
  {
    id: 'major-12-hanged-man',
    deckIndex: 12,
    arcana: 'major',
    suit: null,
    number: 12,
    rank: 'major',
    nameZh: '倒吊人',
    nameEn: 'The Hanged Man',
    uprightKeywordsZh: ['暂停', '换位思考', '放下', '觉察'],
  },
  {
    id: 'major-13-death',
    deckIndex: 13,
    arcana: 'major',
    suit: null,
    number: 13,
    rank: 'major',
    nameZh: '死神',
    nameEn: 'Death',
    uprightKeywordsZh: ['结束', '蜕变', '告别', '重生'],
  },
  {
    id: 'major-14-temperance',
    deckIndex: 14,
    arcana: 'major',
    suit: null,
    number: 14,
    rank: 'major',
    nameZh: '节制',
    nameEn: 'Temperance',
    uprightKeywordsZh: ['平衡', '调和', '节制', '疗愈'],
  },
  {
    id: 'major-15-devil',
    deckIndex: 15,
    arcana: 'major',
    suit: null,
    number: 15,
    rank: 'major',
    nameZh: '恶魔',
    nameEn: 'The Devil',
    uprightKeywordsZh: ['束缚', '欲望', '执念', '阴影'],
  },
  {
    id: 'major-16-tower',
    deckIndex: 16,
    arcana: 'major',
    suit: null,
    number: 16,
    rank: 'major',
    nameZh: '高塔',
    nameEn: 'The Tower',
    uprightKeywordsZh: ['突变', '崩塌', '觉醒', '释放'],
  },
  {
    id: 'major-17-star',
    deckIndex: 17,
    arcana: 'major',
    suit: null,
    number: 17,
    rank: 'major',
    nameZh: '星星',
    nameEn: 'The Star',
    uprightKeywordsZh: ['希望', '灵感', '疗愈', '信念'],
  },
  {
    id: 'major-18-moon',
    deckIndex: 18,
    arcana: 'major',
    suit: null,
    number: 18,
    rank: 'major',
    nameZh: '月亮',
    nameEn: 'The Moon',
    uprightKeywordsZh: ['迷雾', '潜意识', '不安', '想象'],
  },
  {
    id: 'major-19-sun',
    deckIndex: 19,
    arcana: 'major',
    suit: null,
    number: 19,
    rank: 'major',
    nameZh: '太阳',
    nameEn: 'The Sun',
    uprightKeywordsZh: ['喜悦', '成功', '活力', '清晰'],
  },
  {
    id: 'major-20-judgement',
    deckIndex: 20,
    arcana: 'major',
    suit: null,
    number: 20,
    rank: 'major',
    nameZh: '审判',
    nameEn: 'Judgement',
    uprightKeywordsZh: ['觉醒', '召唤', '反思', '复苏'],
  },
  {
    id: 'major-21-world',
    deckIndex: 21,
    arcana: 'major',
    suit: null,
    number: 21,
    rank: 'major',
    nameZh: '世界',
    nameEn: 'The World',
    uprightKeywordsZh: ['完成', '圆满', '整合', '成就'],
  },
  {
    id: 'wands-01-ace',
    deckIndex: 22,
    arcana: 'minor',
    suit: 'wands',
    number: 1,
    rank: 'ace',
    nameZh: '权杖王牌',
    nameEn: 'Ace of Wands',
    uprightKeywordsZh: ['灵感', '新机会', '创造冲动'],
  },
  {
    id: 'wands-02-two',
    deckIndex: 23,
    arcana: 'minor',
    suit: 'wands',
    number: 2,
    rank: 'two',
    nameZh: '权杖二',
    nameEn: 'Two of Wands',
    uprightKeywordsZh: ['规划', '远见', '抉择'],
  },
  {
    id: 'wands-03-three',
    deckIndex: 24,
    arcana: 'minor',
    suit: 'wands',
    number: 3,
    rank: 'three',
    nameZh: '权杖三',
    nameEn: 'Three of Wands',
    uprightKeywordsZh: ['扩展', '进展', '远方'],
  },
  {
    id: 'wands-04-four',
    deckIndex: 25,
    arcana: 'minor',
    suit: 'wands',
    number: 4,
    rank: 'four',
    nameZh: '权杖四',
    nameEn: 'Four of Wands',
    uprightKeywordsZh: ['庆祝', '归属', '稳定'],
  },
  {
    id: 'wands-05-five',
    deckIndex: 26,
    arcana: 'minor',
    suit: 'wands',
    number: 5,
    rank: 'five',
    nameZh: '权杖五',
    nameEn: 'Five of Wands',
    uprightKeywordsZh: ['竞争', '冲突', '磨合'],
  },
  {
    id: 'wands-06-six',
    deckIndex: 27,
    arcana: 'minor',
    suit: 'wands',
    number: 6,
    rank: 'six',
    nameZh: '权杖六',
    nameEn: 'Six of Wands',
    uprightKeywordsZh: ['胜利', '认可', '信心'],
  },
  {
    id: 'wands-07-seven',
    deckIndex: 28,
    arcana: 'minor',
    suit: 'wands',
    number: 7,
    rank: 'seven',
    nameZh: '权杖七',
    nameEn: 'Seven of Wands',
    uprightKeywordsZh: ['坚守', '勇气', '立场'],
  },
  {
    id: 'wands-08-eight',
    deckIndex: 29,
    arcana: 'minor',
    suit: 'wands',
    number: 8,
    rank: 'eight',
    nameZh: '权杖八',
    nameEn: 'Eight of Wands',
    uprightKeywordsZh: ['速度', '消息', '推进'],
  },
  {
    id: 'wands-09-nine',
    deckIndex: 30,
    arcana: 'minor',
    suit: 'wands',
    number: 9,
    rank: 'nine',
    nameZh: '权杖九',
    nameEn: 'Nine of Wands',
    uprightKeywordsZh: ['韧性', '警觉', '坚持'],
  },
  {
    id: 'wands-10-ten',
    deckIndex: 31,
    arcana: 'minor',
    suit: 'wands',
    number: 10,
    rank: 'ten',
    nameZh: '权杖十',
    nameEn: 'Ten of Wands',
    uprightKeywordsZh: ['重担', '责任', '压力'],
  },
  {
    id: 'wands-11-page',
    deckIndex: 32,
    arcana: 'minor',
    suit: 'wands',
    number: 11,
    rank: 'page',
    nameZh: '权杖侍从',
    nameEn: 'Page of Wands',
    uprightKeywordsZh: ['探索', '热情', '好消息'],
  },
  {
    id: 'wands-12-knight',
    deckIndex: 33,
    arcana: 'minor',
    suit: 'wands',
    number: 12,
    rank: 'knight',
    nameZh: '权杖骑士',
    nameEn: 'Knight of Wands',
    uprightKeywordsZh: ['冒险', '冲劲', '行动'],
  },
  {
    id: 'wands-13-queen',
    deckIndex: 34,
    arcana: 'minor',
    suit: 'wands',
    number: 13,
    rank: 'queen',
    nameZh: '权杖王后',
    nameEn: 'Queen of Wands',
    uprightKeywordsZh: ['自信', '魅力', '独立'],
  },
  {
    id: 'wands-14-king',
    deckIndex: 35,
    arcana: 'minor',
    suit: 'wands',
    number: 14,
    rank: 'king',
    nameZh: '权杖国王',
    nameEn: 'King of Wands',
    uprightKeywordsZh: ['领导', '远见', '掌控'],
  },
  {
    id: 'cups-01-ace',
    deckIndex: 36,
    arcana: 'minor',
    suit: 'cups',
    number: 1,
    rank: 'ace',
    nameZh: '圣杯王牌',
    nameEn: 'Ace of Cups',
    uprightKeywordsZh: ['爱的开始', '情感流动', '直觉'],
  },
  {
    id: 'cups-02-two',
    deckIndex: 37,
    arcana: 'minor',
    suit: 'cups',
    number: 2,
    rank: 'two',
    nameZh: '圣杯二',
    nameEn: 'Two of Cups',
    uprightKeywordsZh: ['联结', '互惠', '伙伴'],
  },
  {
    id: 'cups-03-three',
    deckIndex: 38,
    arcana: 'minor',
    suit: 'cups',
    number: 3,
    rank: 'three',
    nameZh: '圣杯三',
    nameEn: 'Three of Cups',
    uprightKeywordsZh: ['友谊', '庆祝', '共享'],
  },
  {
    id: 'cups-04-four',
    deckIndex: 39,
    arcana: 'minor',
    suit: 'cups',
    number: 4,
    rank: 'four',
    nameZh: '圣杯四',
    nameEn: 'Four of Cups',
    uprightKeywordsZh: ['冷淡', '沉思', '重新评估'],
  },
  {
    id: 'cups-05-five',
    deckIndex: 40,
    arcana: 'minor',
    suit: 'cups',
    number: 5,
    rank: 'five',
    nameZh: '圣杯五',
    nameEn: 'Five of Cups',
    uprightKeywordsZh: ['失落', '遗憾', '哀伤'],
  },
  {
    id: 'cups-06-six',
    deckIndex: 41,
    arcana: 'minor',
    suit: 'cups',
    number: 6,
    rank: 'six',
    nameZh: '圣杯六',
    nameEn: 'Six of Cups',
    uprightKeywordsZh: ['回忆', '童真', '重逢'],
  },
  {
    id: 'cups-07-seven',
    deckIndex: 42,
    arcana: 'minor',
    suit: 'cups',
    number: 7,
    rank: 'seven',
    nameZh: '圣杯七',
    nameEn: 'Seven of Cups',
    uprightKeywordsZh: ['选择', '幻想', '诱惑'],
  },
  {
    id: 'cups-08-eight',
    deckIndex: 43,
    arcana: 'minor',
    suit: 'cups',
    number: 8,
    rank: 'eight',
    nameZh: '圣杯八',
    nameEn: 'Eight of Cups',
    uprightKeywordsZh: ['离开', '寻找', '放下'],
  },
  {
    id: 'cups-09-nine',
    deckIndex: 44,
    arcana: 'minor',
    suit: 'cups',
    number: 9,
    rank: 'nine',
    nameZh: '圣杯九',
    nameEn: 'Nine of Cups',
    uprightKeywordsZh: ['满足', '愿望成真', '享受'],
  },
  {
    id: 'cups-10-ten',
    deckIndex: 45,
    arcana: 'minor',
    suit: 'cups',
    number: 10,
    rank: 'ten',
    nameZh: '圣杯十',
    nameEn: 'Ten of Cups',
    uprightKeywordsZh: ['幸福', '家庭', '和谐'],
  },
  {
    id: 'cups-11-page',
    deckIndex: 46,
    arcana: 'minor',
    suit: 'cups',
    number: 11,
    rank: 'page',
    nameZh: '圣杯侍从',
    nameEn: 'Page of Cups',
    uprightKeywordsZh: ['敏感', '创意', '温柔讯息'],
  },
  {
    id: 'cups-12-knight',
    deckIndex: 47,
    arcana: 'minor',
    suit: 'cups',
    number: 12,
    rank: 'knight',
    nameZh: '圣杯骑士',
    nameEn: 'Knight of Cups',
    uprightKeywordsZh: ['浪漫', '邀约', '追随内心'],
  },
  {
    id: 'cups-13-queen',
    deckIndex: 48,
    arcana: 'minor',
    suit: 'cups',
    number: 13,
    rank: 'queen',
    nameZh: '圣杯王后',
    nameEn: 'Queen of Cups',
    uprightKeywordsZh: ['共情', '直觉', '情感成熟'],
  },
  {
    id: 'cups-14-king',
    deckIndex: 49,
    arcana: 'minor',
    suit: 'cups',
    number: 14,
    rank: 'king',
    nameZh: '圣杯国王',
    nameEn: 'King of Cups',
    uprightKeywordsZh: ['情绪平衡', '包容', '外交'],
  },
  {
    id: 'swords-01-ace',
    deckIndex: 50,
    arcana: 'minor',
    suit: 'swords',
    number: 1,
    rank: 'ace',
    nameZh: '宝剑王牌',
    nameEn: 'Ace of Swords',
    uprightKeywordsZh: ['真相', '清晰', '突破'],
  },
  {
    id: 'swords-02-two',
    deckIndex: 51,
    arcana: 'minor',
    suit: 'swords',
    number: 2,
    rank: 'two',
    nameZh: '宝剑二',
    nameEn: 'Two of Swords',
    uprightKeywordsZh: ['僵局', '权衡', '回避'],
  },
  {
    id: 'swords-03-three',
    deckIndex: 52,
    arcana: 'minor',
    suit: 'swords',
    number: 3,
    rank: 'three',
    nameZh: '宝剑三',
    nameEn: 'Three of Swords',
    uprightKeywordsZh: ['心痛', '分离', '悲伤'],
  },
  {
    id: 'swords-04-four',
    deckIndex: 53,
    arcana: 'minor',
    suit: 'swords',
    number: 4,
    rank: 'four',
    nameZh: '宝剑四',
    nameEn: 'Four of Swords',
    uprightKeywordsZh: ['休息', '恢复', '静养'],
  },
  {
    id: 'swords-05-five',
    deckIndex: 54,
    arcana: 'minor',
    suit: 'swords',
    number: 5,
    rank: 'five',
    nameZh: '宝剑五',
    nameEn: 'Five of Swords',
    uprightKeywordsZh: ['冲突', '代价', '胜负'],
  },
  {
    id: 'swords-06-six',
    deckIndex: 55,
    arcana: 'minor',
    suit: 'swords',
    number: 6,
    rank: 'six',
    nameZh: '宝剑六',
    nameEn: 'Six of Swords',
    uprightKeywordsZh: ['过渡', '远离困境', '疗愈'],
  },
  {
    id: 'swords-07-seven',
    deckIndex: 56,
    arcana: 'minor',
    suit: 'swords',
    number: 7,
    rank: 'seven',
    nameZh: '宝剑七',
    nameEn: 'Seven of Swords',
    uprightKeywordsZh: ['策略', '隐秘', '独立行动'],
  },
  {
    id: 'swords-08-eight',
    deckIndex: 57,
    arcana: 'minor',
    suit: 'swords',
    number: 8,
    rank: 'eight',
    nameZh: '宝剑八',
    nameEn: 'Eight of Swords',
    uprightKeywordsZh: ['受限', '困局', '自我束缚'],
  },
  {
    id: 'swords-09-nine',
    deckIndex: 58,
    arcana: 'minor',
    suit: 'swords',
    number: 9,
    rank: 'nine',
    nameZh: '宝剑九',
    nameEn: 'Nine of Swords',
    uprightKeywordsZh: ['焦虑', '失眠', '担忧'],
  },
  {
    id: 'swords-10-ten',
    deckIndex: 59,
    arcana: 'minor',
    suit: 'swords',
    number: 10,
    rank: 'ten',
    nameZh: '宝剑十',
    nameEn: 'Ten of Swords',
    uprightKeywordsZh: ['终结', '触底', '放下'],
  },
  {
    id: 'swords-11-page',
    deckIndex: 60,
    arcana: 'minor',
    suit: 'swords',
    number: 11,
    rank: 'page',
    nameZh: '宝剑侍从',
    nameEn: 'Page of Swords',
    uprightKeywordsZh: ['好奇', '警觉', '求知'],
  },
  {
    id: 'swords-12-knight',
    deckIndex: 61,
    arcana: 'minor',
    suit: 'swords',
    number: 12,
    rank: 'knight',
    nameZh: '宝剑骑士',
    nameEn: 'Knight of Swords',
    uprightKeywordsZh: ['果断', '迅速', '直冲目标'],
  },
  {
    id: 'swords-13-queen',
    deckIndex: 62,
    arcana: 'minor',
    suit: 'swords',
    number: 13,
    rank: 'queen',
    nameZh: '宝剑王后',
    nameEn: 'Queen of Swords',
    uprightKeywordsZh: ['理性', '边界', '坦率'],
  },
  {
    id: 'swords-14-king',
    deckIndex: 63,
    arcana: 'minor',
    suit: 'swords',
    number: 14,
    rank: 'king',
    nameZh: '宝剑国王',
    nameEn: 'King of Swords',
    uprightKeywordsZh: ['思辨', '公正', '权威'],
  },
  {
    id: 'pentacles-01-ace',
    deckIndex: 64,
    arcana: 'minor',
    suit: 'pentacles',
    number: 1,
    rank: 'ace',
    nameZh: '星币王牌',
    nameEn: 'Ace of Pentacles',
    uprightKeywordsZh: ['物质机会', '播种', '繁荣'],
  },
  {
    id: 'pentacles-02-two',
    deckIndex: 65,
    arcana: 'minor',
    suit: 'pentacles',
    number: 2,
    rank: 'two',
    nameZh: '星币二',
    nameEn: 'Two of Pentacles',
    uprightKeywordsZh: ['平衡', '适应', '多任务'],
  },
  {
    id: 'pentacles-03-three',
    deckIndex: 66,
    arcana: 'minor',
    suit: 'pentacles',
    number: 3,
    rank: 'three',
    nameZh: '星币三',
    nameEn: 'Three of Pentacles',
    uprightKeywordsZh: ['协作', '技能', '品质'],
  },
  {
    id: 'pentacles-04-four',
    deckIndex: 67,
    arcana: 'minor',
    suit: 'pentacles',
    number: 4,
    rank: 'four',
    nameZh: '星币四',
    nameEn: 'Four of Pentacles',
    uprightKeywordsZh: ['保守', '占有', '安全感'],
  },
  {
    id: 'pentacles-05-five',
    deckIndex: 68,
    arcana: 'minor',
    suit: 'pentacles',
    number: 5,
    rank: 'five',
    nameZh: '星币五',
    nameEn: 'Five of Pentacles',
    uprightKeywordsZh: ['匮乏', '孤立', '困境'],
  },
  {
    id: 'pentacles-06-six',
    deckIndex: 69,
    arcana: 'minor',
    suit: 'pentacles',
    number: 6,
    rank: 'six',
    nameZh: '星币六',
    nameEn: 'Six of Pentacles',
    uprightKeywordsZh: ['给予', '接受', '公平'],
  },
  {
    id: 'pentacles-07-seven',
    deckIndex: 70,
    arcana: 'minor',
    suit: 'pentacles',
    number: 7,
    rank: 'seven',
    nameZh: '星币七',
    nameEn: 'Seven of Pentacles',
    uprightKeywordsZh: ['耐心', '评估', '长期投入'],
  },
  {
    id: 'pentacles-08-eight',
    deckIndex: 71,
    arcana: 'minor',
    suit: 'pentacles',
    number: 8,
    rank: 'eight',
    nameZh: '星币八',
    nameEn: 'Eight of Pentacles',
    uprightKeywordsZh: ['勤练', '专注', '精进'],
  },
  {
    id: 'pentacles-09-nine',
    deckIndex: 72,
    arcana: 'minor',
    suit: 'pentacles',
    number: 9,
    rank: 'nine',
    nameZh: '星币九',
    nameEn: 'Nine of Pentacles',
    uprightKeywordsZh: ['独立', '收获', '优雅'],
  },
  {
    id: 'pentacles-10-ten',
    deckIndex: 73,
    arcana: 'minor',
    suit: 'pentacles',
    number: 10,
    rank: 'ten',
    nameZh: '星币十',
    nameEn: 'Ten of Pentacles',
    uprightKeywordsZh: ['传承', '财富', '长期稳定'],
  },
  {
    id: 'pentacles-11-page',
    deckIndex: 74,
    arcana: 'minor',
    suit: 'pentacles',
    number: 11,
    rank: 'page',
    nameZh: '星币侍从',
    nameEn: 'Page of Pentacles',
    uprightKeywordsZh: ['学习', '现实计划', '新机会'],
  },
  {
    id: 'pentacles-12-knight',
    deckIndex: 75,
    arcana: 'minor',
    suit: 'pentacles',
    number: 12,
    rank: 'knight',
    nameZh: '星币骑士',
    nameEn: 'Knight of Pentacles',
    uprightKeywordsZh: ['勤勉', '可靠', '稳步前进'],
  },
  {
    id: 'pentacles-13-queen',
    deckIndex: 76,
    arcana: 'minor',
    suit: 'pentacles',
    number: 13,
    rank: 'queen',
    nameZh: '星币王后',
    nameEn: 'Queen of Pentacles',
    uprightKeywordsZh: ['务实', '滋养', '富足'],
  },
  {
    id: 'pentacles-14-king',
    deckIndex: 77,
    arcana: 'minor',
    suit: 'pentacles',
    number: 14,
    rank: 'king',
    nameZh: '星币国王',
    nameEn: 'King of Pentacles',
    uprightKeywordsZh: ['稳健', '成就', '资源管理'],
  },
] as const satisfies readonly TarotCardMeta[]

export const TAROT_CARD_COUNT = TAROT_CARDS.length

export function getTarotCardById(id: string): TarotCardMeta | undefined {
  return TAROT_CARDS.find((card) => card.id === id)
}

export function getTarotCardFacePath(card: Pick<TarotCardMeta, 'id'> | string): string {
  const id = typeof card === 'string' ? card : card.id
  return `${TAROT_CARD_FACE_BASE_PATH}/${id}.webp`
}
