import type { TarotSpread } from './types'

export const TAROT_SPREADS = [
  {
    id: 'single',
    nameZh: '单张指引',
    nameEn: 'Single Card',
    cardCount: 1,
    slots: [
      {
        id: 'guidance',
        order: 1,
        labelZh: '核心指引',
        labelEn: 'Guidance',
        meaningZh: '关键词',
        x: 0.5,
        y: 0.5,
        rotationDeg: 0,
      },
    ],
  },
  {
    id: 'three-card-timeline',
    nameZh: '三张时间流',
    nameEn: 'Past · Present · Future',
    cardCount: 3,
    slots: [
      {
        id: 'past',
        order: 1,
        labelZh: '过去',
        labelEn: 'Past',
        meaningZh: '造成当前局面的背景、根源与已发生影响',
        x: 0.27,
        y: 0.5,
        rotationDeg: -2,
      },
      {
        id: 'present',
        order: 2,
        labelZh: '现在',
        labelEn: 'Present',
        meaningZh: '此刻的核心能量、处境与可用资源',
        x: 0.5,
        y: 0.5,
        rotationDeg: 0,
      },
      {
        id: 'future',
        order: 3,
        labelZh: '未来',
        labelEn: 'Future',
        meaningZh: '若延续当前路径，最可能发展的趋势',
        x: 0.73,
        y: 0.5,
        rotationDeg: 2,
      },
    ],
  },
  {
    id: 'celtic-cross',
    nameZh: '凯尔特十字',
    nameEn: 'Celtic Cross',
    cardCount: 10,
    slots: [
      {
        id: 'present',
        order: 1,
        labelZh: '现状',
        labelEn: 'Present',
        meaningZh: '问题核心与目前主导能量',
        x: 0.34,
        y: 0.5,
        rotationDeg: 0,
        layer: 1,
      },
      {
        id: 'challenge',
        order: 2,
        labelZh: '阻力／助力',
        labelEn: 'Challenge',
        meaningZh: '横跨现状的关键挑战、冲突或推动力量',
        x: 0.34,
        y: 0.5,
        rotationDeg: 90,
        layer: 2,
      },
      {
        id: 'foundation',
        order: 3,
        labelZh: '根基',
        labelEn: 'Foundation',
        meaningZh: '潜意识根源、深层动机与事情基础',
        x: 0.34,
        y: 0.78,
        rotationDeg: 0,
      },
      {
        id: 'recent-past',
        order: 4,
        labelZh: '近因',
        labelEn: 'Recent Past',
        meaningZh: '正在退场但仍影响局面的过去因素',
        x: 0.16,
        y: 0.5,
        rotationDeg: 0,
      },
      {
        id: 'possibility',
        order: 5,
        labelZh: '目标／可能',
        labelEn: 'Possibility',
        meaningZh: '意识层目标、最高可能或关注焦点',
        x: 0.34,
        y: 0.22,
        rotationDeg: 0,
      },
      {
        id: 'near-future',
        order: 6,
        labelZh: '近期未来',
        labelEn: 'Near Future',
        meaningZh: '即将到来的发展与下一阶段影响',
        x: 0.52,
        y: 0.5,
        rotationDeg: 0,
      },
      {
        id: 'self',
        order: 7,
        labelZh: '自我',
        labelEn: 'Self',
        meaningZh: '你的态度、立场、能力与自我认知',
        x: 0.78,
        y: 0.82,
        rotationDeg: 0,
      },
      {
        id: 'environment',
        order: 8,
        labelZh: '环境',
        labelEn: 'Environment',
        meaningZh: '他人、关系与外部环境带来的影响',
        x: 0.78,
        y: 0.62,
        rotationDeg: 0,
      },
      {
        id: 'hopes-fears',
        order: 9,
        labelZh: '希望与恐惧',
        labelEn: 'Hopes & Fears',
        meaningZh: '期待、担忧以及尚未说出口的投射',
        x: 0.78,
        y: 0.42,
        rotationDeg: 0,
      },
      {
        id: 'outcome',
        order: 10,
        labelZh: '结果',
        labelEn: 'Outcome',
        meaningZh: '当前能量延续下去最可能抵达的结果',
        x: 0.78,
        y: 0.22,
        rotationDeg: 0,
      },
    ],
  },
] as const satisfies readonly TarotSpread[]

export type TarotSpreadId = (typeof TAROT_SPREADS)[number]['id']

export function getTarotSpread(id: string): TarotSpread | undefined {
  return TAROT_SPREADS.find((spread) => spread.id === id)
}
